### ISSUE TITLE
Download stuck at 0%

### ISSUE THREAD

**Issue by Boris-Sachet** [Casvt/Kapowarr#115]
**Description of the bug**
Hi, i started using kapowarr on the latest release a month ago, at first everything was fine, i added series, donwloaded some comics, renamed a bunch of existing ones that I imported.
But now every time I auto search or event manual search an issue and download it it gets added to the activity queue and stays at 0%,  0MB/s, status Queued.

I tried to test it with a new series, from a different source, same result.

**To Reproduce**
1. Download an issue, auto or manual
2. Go to activity > Queue
3. Watch the download not moving

**Expected behaviour**
Download starts and finish properly

**Screenshots**
![image](https://github.com/Casvt/Kapowarr/assets/74542867/fe6bd928-dcc4-4a25-82e6-d3f30edc88c9)

**Version info**

Kapowarr version: v1.0.0-beta-3
Python version: 3.8.17.final.0
Database version: 10
Database location: /app/db/Kapowarr.db
Data folder: /app

Container is running on the same raspi as sonarr, radarr and komga who works kind of the same way and fine.

**Comment by Casvt** [comment]
Restart the container. Do they work again then?

**Comment by Boris-Sachet** [comment]
Nope, restaring, destroying the container and recreating it didnt do anything once it was stuck unfortunatelly.

However i've built the image from the dev branch and the situation seems to be better but i don't know if you consider stable enougth to use since there's no release for it?

**Comment by Casvt** [comment]
I'd suggest using the alpha release instead of building from the dev branch. Use `mrcas/kapowarr-alpha:latest`.

It's alpha, but will be beta in a little over a week. In the alpha releases and the next beta release, features that are currently present in beta 3 will be more stable, but new features will be included which will probably have bugs.

**Comment by Boris-Sachet** [comment]
I didn't know there was an alpha docker repo, any reason of not putting on the main repo under a 'alpha' tag?

Anyway I'll try it, thanks :)

**Comment by Casvt** [comment]
Because the alpha versions are released quickly. It would polute the docker repo with all those releases. And I discourage people to use alpha anyway. It's not stable at all and just shouldn't be used unless you want to test for me or need a fix right now. If I would put them in the main repo, people will see them and start using them too soon. This way, people will only use the alpha releases when I tell them about it, which is exactly how I want it to be.
