### ISSUE TITLE
Matching issue searches with one year room

### ISSUE THREAD

**Issue by JaredVanderford** [Casvt/Kapowarr#118]
**Is your feature request related to a problem? Please describe.**
Given the near end of the year and that many comics have a release date vs an instore date and that GetComics uses the in store date, many of the comics in my collection are not being matched and auto downloaded due to a "Year doesn't match" issue. 

**Describe the solution you'd like**
In addition to using the release date, using the in store date for the comic would make it more reliable when doing an auto search to find the correct issues.

**Comment by Casvt** [comment]
In-store date and cover date can differ, at most, 1 year. Kapowarr gives 1 year of room when matching, so you shouldn't experience problems.

Either way, I was planning on converting the whole of Kapowarr to an in-store date application because it's indeed easier when searching on GetComics. The only thing holding me back was one thing: I couldn't find any evidence that GC was consistently using one of the two dates. So:

> ... and that GetComics uses the in store date ...

What is your source? How do you know for sure?

**Comment by Casvt** [comment]
Ah I found the matching bug. I'll fix it soon.
