### ISSUE TITLE
Allow Folder structure in File Naming

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Casvt/Kapowarr#125]
**Is your feature request related to a problem? Please describe.**
I would like to have each issue in a separate folder so that my comic reading app can access them correctly.

**Describe the solution you'd like**
Similar to Volume Folder Naming, which supports folder structure, allow the same for
File Naming
File Naming For TPB
File Naming For Issues Without Title

**Additional context**
NA

**Comment by Casvt** [comment]
I added it and it will be included in the next alpha release. I tried my best to test as many scenarios and configurations to check that it behaves as expected, but there could still be some bugs somewhere. Working with files, folders and filesystems is always very error prone.

For example, I couldn't test if it's working with Mega downloads because it seems like the Mega accounts that GC used have been purged for breaking the terms. So if they come back and the links are fixed it could be the case that Mega downloads lead to errors because I couldn't test them. We'll just have to wait and see.
