### ISSUE TITLE
Better clarity around convert settings

### ISSUE THREAD

**Issue by PhAzE-Variance** [Casvt/Kapowarr#151]
**Is your feature request related to a problem? Please describe.**
It's difficult to understand the convert settings, since there is a drop down that seemingly doesn't do anything (see attached image). 

**Describe the solution you'd like**
Drop down should be removed, so level 1 defaults to "No Conversion" and when you click the + symbol to add new conversions, it's easier to understand.

**Additional context**
Attached image shows the button that appears to do nothing and there's no documentation around this.
![convert](https://github.com/Casvt/Kapowarr/assets/3928578/7245dd20-ff6f-4588-90a9-5b67bb53dd23)

**Comment by Casvt** [comment]
You select the format and then click the plus button to add it to the preference list.

I agree that it's not perfect, but I couldn't come up with something better. I don't understand the solution that you're proposing. Could you elaborate?

**Comment by PhAzE-Variance** [comment]
For sure, I think you shouln't have that drop down at the bottom, just the + to add a new conversion type. When a user clicks the plus, the new row shows with it's own drop down for the user to select the type.

**Comment by Casvt** [comment]
I thought about it, and what you're proposing could make it more confusing actually. Because, if I understand it correctly, there would be a `+` button next to the `No Conversion` which would toggle the next row which contains the dropdown for the format to be added. But then there needs to be a second `+` button next to the dropdown that you click to add the format that you've selected. So then you get two `+` buttons below each other and that's honestly even more confusing.

So what about this:

The 'No Conversion' row is actually a dropdown. If you change the value from 'No Conversion' to a different format, then it gets added to the list and the 'No Conversion' dropdown get's moved down one row and is set back to 'No Conversion'. How does that sound? Then we have not two, not one, but zero buttons. Just a drop down that you can select from and it automatically creates the space to add another one and so on.

**Comment by PhAzE-Variance** [comment]
Yeah that works too. Each row would need way to be removed too.

**Comment by Casvt** [comment]
Yeah but that can be done with the bin icon to the right of each row that already exists

**Comment by Casvt** [comment]
Turned out to be a pretty easy fix. See the video:

https://github.com/Casvt/Kapowarr/assets/88994465/97fe8083-6b27-4511-b2e2-b8e2b7bf2e7d
