### ISSUE TITLE
Converting comics should only convert known files

### ISSUE THREAD

**Issue by PhAzE-Variance** [Casvt/Kapowarr#153]
**Is your feature request related to a problem? Please describe.**
The way Kapowarr converts files appears to take all files in the directory and run them through the convert functions. This can cause issues if unknown filetypes exist in the directory, including comictagger files.

**Describe the solution you'd like**
The convert process should only convert known files that it expects, being ones that are tracked by Kapowarr and of known file types, while everything else is ignored. This will allow extra info / metadata files to remain and not break the convert process when mass converting or downloading new.

**Additional context**
N/A

**Comment by Casvt** [comment]
Already fixed.

Both in your version and my development version, Kapowarr starts of with only converting files that are actually recognised (extension and matched).

The difference is that in your version, when an archive file is extracted because it contains multiple issues, then [all the files in the folder are converted](https://github.com/Casvt/Kapowarr/blob/V1.0.0-beta-4/backend/conversion.py#L262) in an attempt to convert the extracted files. That is fixed in the development version, where [only the files actually extracted from the archive are processed](https://github.com/Casvt/Kapowarr/blob/development/backend/conversion.py#L204) instead of all files in the folder.
