### ISSUE TITLE
Queue is frozen 

### ISSUE THREAD

**Issue by FBoucher** [Casvt/Kapowarr#158]
The queue seams frozen. I restarted the container, refresh the queue, clear the temp folder... but nothing changes. it's been importing the same comics for days, the cancelled job are always present (in fact I think they get re-activated somehow)

This long list of frozen tasks prevent the download of anything else. Should I just delete the DB and start over?

**Screenshots**

![image](https://github.com/Casvt/Kapowarr/assets/2404846/44a142dd-e548-4bd6-9df8-d92d05a34984)

**Version info**

Kapowarr version	v1.0.0-beta-4
Python version	3.8.17.final.0
Database version	14
Database location	/app/db/Kapowarr.db
Data folder	/app

Running In Docker on a Debian host.

**Comment by Casvt** [comment]
Check the logs, there probably is an error somewhere which stopped the handling of the queue.

To empty the queue, have the container running, then run the following commands:

```bash
docker exec -it kapowarr /bin/bash

python3 -c "import sqlite3; sqlite3.connect('db/Kapowarr.db').cursor().execute('DELETE FROM download_queue').connection.commit()"

exit
```

That's three commands. Then restart the container.

**Comment by FBoucher** [comment]
It worked!
May I suggest a button from the UI to do that easily?

For Info the log was saying the folder already contained files. It make sense because it was folder that I imported.

**Comment by Casvt** [comment]
Adding a button is avoiding the problem instead of fixing it. The error should instead be fixed, because then the queue won't break. Your description of the error is a bit vague (it would be better if you shared the error directly from the logs), however it seems like you're describing the error that the file already exists or that the file doesn't exist. There is a bug in the latest public version where files that already exist aren't properly replaced but instead raise an error. It's fixed already, but the fact that Kapowarr was downloading files that already were downloaded is strange of course. However, that could be because of another bug (that is also already fixed), where Kapowarr would accidentally download HTML files that won't match to the issue.

All in all, everything you're experiencing is most likely already fixed and these fixes will be included in the next release. But I can only be certain if you share the actual error.

A button to clear the queue wouldn't fix the problem (like you're suggesting), because the commands that you ran cleared the queue, but the restarting of the container is what spun the queue handler back up. So simply clearing the queue wouldn't help, you also need to restart to container.
