### ISSUE TITLE
Changeable File Paths

### ISSUE THREAD

**Issue by DaveAlton** [Casvt/Kapowarr#20]
**Is your feature request related to a problem? Please describe.**
Yes, I can't name my folders anything I'd like. For Star Wars comics, I remove the "Star Wars" prefix from the volume name because they all have that prefix so it's pointless to include. 

**Describe the solution you'd like**
Use the Sonarr/Radarr way of folder setting. Allow me to just select a file path.

**Additional info**
Only flat folder structures are supported. If I want to store any set of volumes inside a folder, I have to create a whole new root folder for it. 
Because of all the above reasons I can only use Kapowarr for some or my comics and not all.

**Comment by Berserkir-Wolf** [comment]
That's doable.
Volume folder naming: `{series_name}`
File naming: `Volume {volume_number} ({year})\Issue {issue_number}`
This would result in a `Star Wars` folder, with files being in volume subfolders by year, ending like this:  
`Star Wars\Volume 2 (2003)\Issue 127.cbz`

**Comment by DaveAlton** [comment]
The catch is that each volume needs to be different. I want the ability to have a folder with:

Star Wars/Star Wars (2015)/Star Wars 001 (2015)

Star Wars/Star Wars (2020)/Star Wars 001 (2020)

Star Wars/The High Republic (2015)/Star Wars The High Republic 001 (2020)

The catch is that the last instance is technically named "Star Wars The High Republic".

**Comment by Casvt** [comment]
> That's doable.
> Volume folder naming: `{series_name}`
> File naming: `Volume {volume_number} ({year})\Issue {issue_number}`
> This would result in a `Star Wars` folder, with files being in volume subfolders by year, ending like this: `Star Wars\Volume 2 (2003)\Issue 127.cbz`

It should be:

- Volume folder naming: `{series_name}\Volume {volume_number} ({year})`
- File naming: `Issue {issue_number}`

Because the File naming doesn't allow folder structure while Volume folder naming does.

But that aside, @DaveAlton you basically want custom volume folders? Being able to manually set a folder instead of having one auto-generated?

**Comment by DaveAlton** [comment]
Exactly. Having the option to be manual would solve my problems.

**Comment by Casvt** [comment]
I'm working on that right now :)

**Comment by hwwilliams** [comment]
I wasn't sure if I should make another issue since this sounds very similar but I would also appreciate allowing the same series over several years to be stacked under a single series name as [Kavita](https://github.com/Kareadita/Kavita) is using this approach for displaying a single series and it looks great, Kavita uses the comicinfo.xml for most comic information but if there are multiple series of the same name in different directories it doesn't work at all.

Similar to this:

`Wolverine\Wolverine V1982 v2 001`
`Wolverine\Wolverine V2003 v2 001`
`Wolverine\Wolverine V2010 v3 001`
`Wolverine\Wolverine V2014 v5 001`
`Wolverine\Wolverine V2020 v6 001`

![image](https://github.com/Casvt/Kapowarr/assets/20447447/c62e604e-c87e-4c56-ba94-25720d570c9c)

**Comment by Casvt** [comment]
Kapowarr extracts data from `The Mandalorian/Doctor Who (1963) V07 C09.cbr` in the following way:
```python3
{
    "series": "Doctor Who",
    "year": 1963,
    "volume_number": 7,
    "special_version": null,
    "issue_number": 9.0,
    "annual": false
}
```

**Comment by hwwilliams** [comment]
> I'll let @Casvt reply with their thoughts, but would Kavita recognize it if it was maybe just in a sub folder?

I'd have to double check on the subfolder idea for Kavita, this kind of file structure is also not supported by Mylar either and so I have my own python scripts that run on each file after post-processing is finished to move them into a final library structure.

> I know it's a lot of work to migrate libraries, but have you considered Komga? I personally found it to be way better for comics and I know others have moved over to it for the same reason.

I actually migrated away from Komga to Kavita because I found Komga to be extremely slow (60k issues) with a high number of comics even when libraries are split by publisher whereas once Kavita did its initial scans it's very snappy. I also appreciate the built-in library metrics that Kavita provides.

**Comment by hwwilliams** [comment]
> Kapowarr extracts data from `The Mandalorian/Doctor Who (1963) V07 C09.cbr` in the following way:
> 
> ```python
> {
>     "series": "Doctor Who",
>     "year": 1963,
>     "volume_number": 7,
>     "special_version": null,
>     "issue_number": 9.0,
>     "annual": false
> }
> ```

So it sounds like the Kavita file structure would work? Maybe I'm misunderstanding but either way I'm glad to see new people working on this kind of software as Mylar has been the only real option for too long.

**Comment by DaveAlton** [comment]
Thanks so much @Casvt!
