### ISSUE TITLE
Error when pressing Preview Rename

### ISSUE THREAD

**Issue by YaibaToKen** [Casvt/Kapowarr#204]
**Description of the bug**

Pressing Preview Rename on some volumes does nothing, despite files being detected and not conforming to defined format.

**To Reproduce**

1. Press Preview Rename

**Expected behaviour**

Preview Rename should open a popup with predicted changes asking for confirmation.

**Version info**

![image](https://github.com/user-attachments/assets/9f663e00-6343-460f-a48c-3fcc358039af)

**Additional context**

```
:40m[11:09:26][ERROR] Exception on /api/volumes/463/rename [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/frontend/api.py", line 78, in wrapper
    return method(*args, **kwargs)
  File "/app/frontend/api.py", line 234, in wrapper
    result = method(*args, **kwargs)
  File "/app/frontend/api.py", line 716, in api_rename
    result = preview_mass_rename(id)[0]
  File "/app/backend/naming.py", line 564, in preview_mass_rename
    suggested_name = generate_empty_name(
  File "/app/backend/naming.py", line 273, in generate_empty_name
    sv_l.remove('None')
ValueError: list.remove(x): x not in list
```

**Comment by Casvt** [comment]
Your naming format for special versions doesn't have the `{special_version}` key in it, even though it should have it.

**Comment by YaibaToKen** [comment]
Why are we expecting files that have been matched but not renamed to conform with a specific naming scheme?

**Comment by Casvt** [comment]
They don't have to conform to the format. But you're trying to rename the files so that they _become_ conform to the format. But one of the formats that the files will be renamed to is invalid, so it fails loading the proposed names.

**Comment by Casvt** [comment]
Bit unrelated, but `#{special_version}` probably isn't what you want, as that would result in something like `#TPB` or `#One-Shot`.

Basic validation is done to check if the variables used actually exist (e.g. using `{foo}` would not be allowed). Checking if required variables are present is harder though because different combinations of variables are sufficient to match the files. For example, the volume number is not required in the file name if it's already in the folder name.

I've had on my to-do list for quite some time now to use the entered formats to create fake filenames and test on them to see if the formats are sufficient for Kapowarr. If not reject them (show an error). This would catch the missing special version variable for example. I'm planning on adding this in the next few days.

And further into the future, I'll add a format builder similar to the one on other other arrs that'll give a live preview as you're typing your format.
