### ISSUE TITLE
Filter wanted languages

### ISSUE THREAD

**Issue by Cassock** [Casvt/Kapowarr#25]
**Is your feature request related to a problem? Please describe.**
Searching for comics from `/add` results in a lot of translations

**Describe the solution you'd like**
Check boxes here or in the Settings pages that would toggle desired languages in the results

**Additional context**
Sadly I don't think CV has this info, so may need to parse the descriptions

**Comment by Casvt** [comment]
I think I might be able to do something. Like a "Filter out translated versions" option?

**Comment by Cassock** [comment]
Yeah, something like that. Personally I'm only interested in English versions of anything, but I'm sure there are others who would like a TWD translated into German or a Japanese Spider-man or whatever in their native language. Sonarr does this with Language profiles:
![image](https://github.com/Casvt/Kapowarr/assets/15901832/a543fc1c-d8d7-493e-902b-6e75cca8e4af)

**Comment by Casvt** [comment]
I added a filter at the top when searching for volumes that allows the user to filter out what Kapowarr thinks is a translated version, based on the description. It's definitely not perfect. You can only choose between "All Languages" and "Only English". And Kapowarr uses the description, which isn't perfect because there are loads of translations that don't have a description. 

However, it does the job decently. I'll keep it like this for now and await user response. If enough people want a better version of this, I'll invest time into it, but if not I'll leave it like this.

See images below:
![image](https://github.com/Casvt/Kapowarr/assets/88994465/1b622c8a-7e9d-4692-95c5-96b258c80eb1)
![image](https://github.com/Casvt/Kapowarr/assets/88994465/4ca74896-88b7-437c-9209-d34a1899e5c9)
