### ISSUE TITLE
Only download TPB's for TPB releases

### ISSUE THREAD

**Issue by ItsNoted** [Casvt/Kapowarr#27]
I think one thing confusing people is Kapowarr prioritizes TPB over single issues. It downloads a single TPB marking all the issues as downloaded. For me, that is fine but others may like single issues as small file sizes instead of downloading the full TPB at a larger file size.

So an option to choose which volume type to prioritize would be nice. TPB or Single Issue on downloads.

**Comment by Casvt** [comment]
This actually comes down to a different problem.

ComicVine has separate entries in it's database for TPB releases of (part of) volumes. So Kapowarr shouldn't download a TPB in _any_ case, _unless_ the volume is specifically a TPB-volume of ComicVine, often only having one "issue": the TPB. 

Take "Silver Surfer Rebirth" for example. On ComicVine, you have the normal "issue release" ([link](https://comicvine.gamespot.com/silver-surfer-rebirth/4050-141331/)), but you also have a "TPB release" ([link](https://comicvine.gamespot.com/silver-surfer-rebirth/4050-147555/)). So if you add an issue-release, Kapowarr shouldn't download any TPB at all for it, and vice versa. And thus we'll never have a situation where we can download a TPB or a set of issues for the same ComicVine release. So also no need to implement some sort of "preference".

The reason that I didn't make Kapowarr work like this on release, is because at the time I didn't know ComicVine did it like this.

**Comment by bl4ckph0en1x** [comment]
+1 on not downloading TPB.

**Comment by Casvt** [comment]
@bl4ckph0en1x

The best way to know what the ETA is of something, is to check the [project board](https://github.com/users/Casvt/projects/5). You'll see that it's almost at the top of "Handled Soon", which means that it'll almost be the very next thing that will be fixed.
