### ISSUE TITLE
Add websocket connection to UI for live UI updates

### ISSUE THREAD

**Issue by Andrewpaps** [Casvt/Kapowarr#43]
**Description of the bug**
Library not updating after search until page refresh

**To Reproduce**
1. Add or download item
2. Cross mark will not become check mark until page refresh

**Expected behaviour**
Check mark will appear after file recognition.

**Comment by Casvt** [comment]
The reason this isn't implemented yet is that the UI would need to constantly check the queue for if an item is downloaded and then change the check mark. This is quite resource intensive because we would need to constantly make requests (like every second).

This is already happening for tasks that appear at the bottom left in the nav bar and when viewing the queue to keep the queue updated.

A better solution would be to setup a websocket connection between the UI and the backend with which a constant connection can be kept to send live updates to the UI by the backend. Then no constant requests have to be made for anything.

**Comment by Andrewpaps** [comment]
Nice, sounds like a good implementation.
