### ISSUE TITLE
Feature Request: Implement ability to download via torrent download clients

### ISSUE THREAD

**Issue by winterborn** [Casvt/Kapowarr#48]
Feature Request: Implement ability to download via torrent download clients as per Sonarr, Radarr etc.

**Comment by Casvt** [comment]
You're referring to adding indexers and torrent clients and downloading using that "ecosystem", as an alternative to downloading from GetComics. Implementing this can be split up into two parts, of which one you're actually naming here with this issue:

1. Adding support for torrent download clients
2. Adding support for indexers as alternative sources of torrents

You could say that it can be split up in _downloading_ torrents and _getting them_. Because GetComics sometimes offers torrents as a way to download a release, I can fully implement bullet 1 before needing to implement bullet 2.

**Comment by bl4ckph0en1x** [comment]
This should be priority. See #73
