### ISSUE TITLE
Multiple file Renaming choices per volume

### ISSUE THREAD

**Issue by opicron** [Casvt/Kapowarr#78]
I would like Kapowarr to rename all my comics. 
Some metadata have issue titles, some have none and some have 'Volume x' as titles.

Meaning I get the following variation results:

{title} {year} Volume {x} Issue {xxx} - Unknown (when empty title)
{title} {year} Volume {x} Issue {xxx} - Volume x (when 'volume' as title}
{title} {year} Volume {x} Issue {xxx} - Real title (with a correct title)

Would it be possible to set a default rename regex, and also a per volume rename regex?

This way we can add titles only to volumes (comics) which actually have them. Or add an option to avoid adding {title} when the title is 'volume' or empty (unknown).

A leading zero 1 or 2 zeros would be awesome too as very low priority.

**Comment by Casvt** [comment]
Ah I understand.

> Would it be possible to set a default rename regex

You can already do this. In the web-ui, go to Settings -> Media Management -> File Naming. There you can change the naming format for the volume folder, issue and TPB.

> and also a per volume rename regex?
> This way we can add titles only to volumes (comics) which actually have them. Or add an option to avoid adding {title} when the title is 'volume' or empty (unknown).

My plan is:

1. Add a regex in the settings (Settings -> Media Management -> File Naming) that people can set for issues where no title is desired (e.g. `{series_name} ({year}) Volume {volume_number}`)
2. On/Off option in settings that tells Kapowarr whether or not to use the above special regex in case it encounters Unknown or Volume X

Does that sound good?

**Comment by Casvt** [comment]
Added special naming for files of issues that don't have a title. Also added an option that makes Kapowarr name files as no-title files if their issue title is "Volume N".

That last addition is currently quite useless, because volumes that are a collection of volumes (issues named "Volume N") are not supported by Kapowarr currently. However, that is being worked on (#56) and when that is finished, this addition will fit in nicely.
