### ISSUE TITLE
Failing to download all GC links

### ISSUE THREAD

**Issue by therobbiedavis** [Casvt/Kapowarr#82]
**Description of the bug**
Kapowarr does not download all links from getcomics, just the first found

**To Reproduce**

1. Add the volume in Kapowarr "Batman (1940) Volume 1"
2. Click on "Search Monitored"
3. See that Kapowarr finds "https://getcomics.org/dc/batman-vol-1-0-713-annuals-extras-1940-2011/"
4. See that Kapowarr only downloads "Batman 000 – 010 (1940-1942 + 1994) (599 MB)"

**Expected behaviour**
I would expect in a case like this, which GC often splits up larger collections like this, that Kapowarr would iterate over the links and download then all.

**Version info**
v1.0.0-beta-2
Docker, Chrome

**Comment by Casvt** [comment]
> I would expect in a case like this, which GC often splits up larger collections like this, that Kapowarr would iterate over the links and download then all.

Kapowarr normally does this. The problem seems to be that the years don't match with the volume release year except for the first download. Kapowarr should check if the years mentioned are between release year and the year of the last issue instead of just the release year. In beta-1, the year wasn't checked at all but I added a check in beta-2. I just forgot that the year check should span the whole volume lifetime instead of just the release year.

**Comment by Casvt** [comment]
Fixed. This fix will be included in the next release. I'll fasten beta-3 seeing that this bug has quite the impact on the workings of Kapowarr.
