### ISSUE TITLE
DB locked when trying to add volume through API

### ISSUE THREAD

**Issue by bill-roemhild** [Casvt/Kapowarr#87]
**Description of the bug**
When adding volumes in rapid succession using the API:

call:
curl --location '192.168.200.62:5656/api/volumes' \
--header 'Content-Type: application/json' \
--data '{"comicvine_id": "4050-149812",
 "root_folder_id": 1}'

returns:
{"error":"InternalError","result":{}}

log:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/frontend/api.py", line 55, in wrapper
    return method(*args, **kwargs)
  File "/app/frontend/api.py", line 379, in api_volumes
    volume_id = library.add(comicvine_id, root_folder_id, monitor, volume_folder)
  File "/app/backend/volumes.py", line 599, in add
    cursor.execute(
sqlite3.OperationalError: database is locked

**Expected behaviour**
Volume should be added to db.

**Version info**

Kapowarr version	v1.0.0-beta-2
Python version	3.8.17.final.0
Database version	7

**Comment by Casvt** [comment]
Two things could've happened that triggered this error:
1. You sent all requests asynchronously, which means that Kapowarr needs to add multiple volumes at the same time.
2. A "Refresh & Scan" or "Update All" was triggered (manually or by Kapowarr) while making these requests.

They both result in the same thing: multiple things tried to update the database at the same time, the database tries to handle all requests one by one (because it can only write one thing at the same time), gives all writes except one a timeout, and the waiting requests exceeded the 20s timeout, leading to the error. Basically, writes to the database were waiting for more than 20s in the "queue" to write to the database.

It's hard to fix because the database already has it's journal mode set to WAL mode, which improves write speeds and concurrency the most. And actions that take a lot of writes already commit in the middle, so that other writes in the queue can get through before those actions continue.

**Comment by billroemhild** [comment]
The requests to add volumes were synchronous.  

Wondering if it is possible to extend the timeout longer?  I haven't used WAL before, is there a fear of losing DB updates if a restart happens?

**Comment by Casvt** [comment]
The request to add a volume was the one to time out. That means that at the same time, something else was writing to the database (and not committing in the mean time) for more than 20 seconds, which made the request to add the volume time out. The only things in general that could've been taking more than 20s to complete could be adding a volume and an "Update All" or "Refresh & Scan". The first one is not possible because you were adding them synchronously.

I'm planning on refactoring the whole backend soon and I see some places where code can be sped up, leading to shorter times writing to the database and shorter times between commits, leading to less "chance" to encounter a timeout.

> Wondering if it is possible to extend the timeout longer?

For sure, but that's avoiding the problem instead of fixing it. Certain actions are "claiming" the database for a long time (20+ seconds). Those actions should be fixed so that they don't claim the database for so long, instead of making the rest wait even longer. We should make the slowest faster, not the fastest slower.

> I haven't used WAL before, is there a fear of losing DB updates if a restart happens?

The journal mode of a database determines how something is written to the database. In WAL mode, all new writes to a database are written to a separate database file. These two (or sometimes three) database files live along side each other while Kapowarr is running.

If Kapowarr is shut down properly, the original database file and the WAL file (with all the new updates and additions) will be merged into one database file again.

If you abruptly shut down Kapowarr, it doesn't have the chance to "clean up" the database files. You'll be left with two or three database files. There is nothing wrong with that; the next time that you start up Kapowarr they will merge again. But until you start Kapowarr up again, you'll have multiple database files and Kapowarr needs all of them to not loose data. It's not bad, but not advised because you need to keep all three files to save data. If you shutdown Kapowarr properly, you'll just have one nice database file containing everything.
