### ISSUE TITLE
Having volume number after issue number in filename not working

### ISSUE THREAD

**Issue by opicron** [Casvt/Kapowarr#94]
**Description of the bug**
Multiple issues linked to one issue.

**To Reproduce**
Not sure how to reproduce.

**Expected behaviour**
When hitting refresh and scan, I expected the issues to be linked correctly to all issues.

**Screenshots**
![Screenshot 2023-09-12 202106](https://github.com/Casvt/Kapowarr/assets/472432/704b3402-50b2-4176-8291-27bcb9d20ab9)

Version info
Kapowarr v1.0.0-beta-3
Python 3.8.17.final.0

**Comment by Casvt** [comment]
It's because of the fact that the volume number is to the right of the issue number. It's like saying "episode 5 season 6" instead of "season 6 episode 5". I'll see if I can fix it.

**Comment by opicron** [comment]
If you need any help with some regex patterns. I'm pretty good with them.

**Comment by Casvt** [comment]
The regexes are working well. It's more the "logic" in the algorithm that is failing. It is correctly extracting the volume number. However, the algorithm then searches for the issue number to the right of the volume number. But for your case it will then never find it.

It _should_ search for the issue number on the right side of the volume number. However, if it doesn't find it, it should also check to the left as a fallback instead of just not finding it.

**Comment by Berserkir-Wolf** [comment]
Can the regex check for the words "issue" and "volume" as a further fallback?

**Comment by Casvt** [comment]
It already does. As I said, the regex is working fine. It's the logic that is failing here.

**Comment by Casvt** [comment]
Fixed it. Will be included in next release.
